Feature/create offer interface
hashgreen/hoogii-wallet pull request #89
Opened 2023-02-01 08:51 UTC by ahwei

# Description

create offer interface
Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-02-06 03:31 UTC, ahwei commented on src/utils/Secure.ts
> +            return
throw error

2023-02-06 03:31 UTC, ahwei commented on src/utils/Secure.ts
> +            return
throw error

2023-02-06 03:31 UTC, hryjosn requested changes

2023-02-06 03:31 UTC, hryjosn commented on src/utils/Secure.ts
> +            return
Maybe can throw error

2023-02-06 03:31 UTC, hryjosn commented on src/utils/Secure.ts
> +            return
Maybe can throw error

2023-02-06 03:33 UTC, hryjosn requested changes

2023-02-06 03:33 UTC, hryjosn commented on src/utils/puzzles.ts
> +        'ff02ffff01ff02ff5effff04ff02ffff04ffff04ff05ffff04ffff0bff2cff0580ffff04ff0bff80808080ffff04ffff02ff17ff2f80ffff04ff5fffff04ffff02ff2effff04ff02ffff04ff17ff80808080ffff04ffff0bff82027fff8205
add constant to json file

2023-02-07 04:44 UTC, hryjosn requested changes
Please modify request changes

2023-02-07 04:44 UTC, hryjosn commented on popup.html
> +        <meta name=”viewport”>
wrong symbol

2023-02-07 04:44 UTC, hryjosn commented on src/popup/pages/transaction.tsx
> +                        const amount = !asset.assetId
reverse order of condition

2023-02-07 04:44 UTC, hryjosn commented on src/utils/CAT.ts
> +        console.log(
remove console.log()

2023-02-07 04:44 UTC, hryjosn commented on src/utils/Offer.ts
> +    static async createCoinSpend() {}
remove this plz

2023-02-07 04:44 UTC, hryjosn commented on src/utils/Offer.ts
> +                console.log('settlement.hashHex()', settlement.hashHex())
remove console.log()

2023-02-07 04:44 UTC, hryjosn commented on src/utils/Offer.ts
> +            if (assetId) {
remove duplicated logic

2023-02-07 04:44 UTC, hryjosn commented on src/utils/Offer.ts
> +                            'ae83525ba8d1dd3f09b277de18ca3e43fc0af20d20c4b3e92ef2a48bd291ccb2',
replace with constant: agg_sig_me_additional_data

2023-02-07 04:44 UTC, hryjosn commented on src/utils/Secure.ts
> +            const puzzleReveal = getProgramBySeed(seed)
Rename variable as `puzzle`

2023-02-07 04:44 UTC, hryjosn commented on src/utils/Wallet/types.ts
> +    targetAddress?: string
remove targetAddress

2023-02-09 01:42 UTC, hryjosn requested changes

2023-02-09 01:42 UTC, hryjosn commented on src/api/extension/request.ts
> +const createOffer = async (res: { offer: string }) => {
Continuely modify this

2023-02-17 06:46 UTC, hryjosn approved these changes

2023-02-17 06:47 UTC, merged